FROM pytorchlightning/pytorch_lightning:base-cuda-py3.12-torch2.6-cuda12.4.1

WORKDIR /workspace

COPY pyproject.toml .
COPY *.yaml ./

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:$PATH"

RUN uv sync

# Fetch inference artifact
RUN uv pip install awscli

#ENTRYPOINT
#CMD
